apiVersion: apps/v1
kind: Deployment
metadata:
  name: site

spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: site
        image: site:latest

        ports:
        - containerPort: 80
          name: http

        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 200Mi